# -*- coding: utf-8 -*-
"""supplem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jdztpkL3Uodcj92kbci-uun9fg_lGOvL
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mylib.py
# def testf():
#   print('it works')

testf()